name: Build and Deploy to CloudFront
on:
  push:
    branches: [ development ] // you main branch
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    env:
      BUCKET: nextjs-s3-cloudfront-icareer
      DIST: out
      REGION: ap-southeast-2
      DIST_ID: E1YKD2WG0RQT0A

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AKIA3FLD5TGMZDPLC5FY }}
        aws-secret-access-key: ${{ secrets.goP/mZaWp7DJ8O0sBpRJPYEUVCSsjV5WJi8znUSq }}
        aws-region: ${{ ap-southeast-2 }}

    - name: Install Dependencies
      run: |
        node --version
        npm ci --production

    - name: Build Static Website
      run: npm run build

    - name: Copy files to the production website with the AWS CLI
      run: |
        aws s3 sync --delete ${{ env.DIST }} s3://${{ env.BUCKET }}

    - name: Copy files to the production website with the AWS CLI
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ env.DIST_ID }} \
          --paths "/*"