name : CI Pipeline

on:
  push:
    branches:
      - development
      
jobs:
  build:
    runs-on: ubuntu-latest
    environment: STAGING

    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20.14.0'
      
      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: npm run build

      - name: Docker build
        run: docker build -t psoakun/fp-pso .

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish Image to DockerHub
        run: docker push psoakun/fp-pso:latest
  
      - name: Docker run (for development purpose)
        run: docker run -d -p 3000:3000 psoakun/fp-pso

      - name: Wait for application to start
        run: sleep 10  
  
      - name: Check if app is running (basic health check)
        run: curl -f http://localhost:3000 || exit 1

  test:
    runs-on: ubuntu-latest
    environment: STAGING
    needs: build  

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20.14.0'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test
      