name : CI Pipeline

on:
  push:
    branches:
      - development
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20.14.0'
      
      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: npm run build

      - name: Run Test
        run: npm test
      
      - name: Docker build
        run: docker build -t icareer .
  
      - name: Docker run (for development purpose)
        run: docker run -d -p 3000:3000 icareer
  
      - name: Check if app is running (basic health check)
        run: curl -f http://localhost:3000 || exit 1
      