name : CICD Pipeline

on:
  push:
    branches:
      - main
      - staging
      - development
      
jobs:
  build:
    runs-on: ubuntu-latest



    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20.14.0'
      
      - name: Install Dependencies
        run: npm install

      - name: Setup Environment Variables
        run: echo "SITE_URL=${{ secrets.SITE_URL }}" >> .env

      - name: Build App
        run: npm run build

      - name: Docker build
        run: docker build -t psoakun/fp-pso .

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish Image to DockerHub
        run: docker push psoakun/fp-pso:latest


  test:
    runs-on: ubuntu-latest

    needs: build  

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20.14.0'

      - name: Install dependencies
        run: npm install

      - name: Testing App
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: test  

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.8.5"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: AKIA3FLD5TGM3YFTURRH
          aws-secret-access-key: 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
          aws-region: ap-southeast-2
          
      - name: Initialize Terraform
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=plan.out

      - name: Terraform Apply
        run: terraform apply plan.out
        env:
          TF_VAR_access_key: AKIA3FLD5TGM3YFTURRH
          TF_VAR_secret_key: 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
