name : Deploy Next.js application 

on:
  push:
    branches:
      - development
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env && echo "SITE_URL=${{ secrets.SITE_URL }}" >> .env
      - name: Build docker image
        run: docker build -t njul/fp-pso .
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish image to docker hub
        run: docker push njul/fp-pso:latest


  deploy:
    needs: build
    runs-on: self-hosted  
    steps:
      - name: Pull image from docker hub
        run: docker pull njul/fp-pso:latest
      - name: Delete old container
        run: docker rm -f fp-pso-container 
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name fp-pso-container njul/fp-pso